CI: Use upper constraints to install clients
Stein & earlier only

Some dependencies of client libraries (openstacksdk) have released
packages which do not support Python 2, but are not marked as such,
meaning that pip will install them. This breaks when the clients are
used, in this case in init-runonce:

    ImportError: No module named queue

This change fixes the issue by using upper constraints when installing
the clients.

This change also increases the timeout when waiting for Horizon to
start in CI, since it seems to now take a long time to compress static
files.

Change-Id: I3272c0b8ebf6be957c120714a826a615246aa16b
Related-Bug: #1870349