Synchronise kolla-ansible installation with other branches
In stable/train, installing kolla-ansible system-wide on CentOS 8 failed
with:

    ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed
    project and thus we cannot accurately determine which files belong
    to it which would lead to only a partial uninstall.

This change switched to using pip --user when installing kolla-ansible,
as done in change Ifaf1948ed5d42eebaa62d7bad375bbfc12b134d5.

This is cherry-picked to stable/ussuri so that all supported branches
use similar code.

Change-Id: I4ac15e8ac4e2484e4aee0e942fabc2453a09d168
(cherry picked from commit a919fbcc3517ed355221e3d6888e6806616a40e8)