CI: fix kolla-ansible installation after cryptography 3.4 release
Installing kolla-ansible system-wide on CentOS 8 fails with:

    ModuleNotFoundError: No module named 'setuptools_rust'

This error appeared following the release of cryptography 3.4, which now
includes Rust code. It can be installed without Rust using a Python
wheel, but only with more recent pip than version 9.0.3 available as RPM
on CentOS 8. The cryptography bug report [1] recommends pip>=19.1.1.

This change switches to using pip --user when installing kolla-ansible.

Also fixes an issue with ansible-lint which was failing on
etc/kolla/globals.yml due to a missing space before comments.

This Victoria backport also includes
I47473de6f71c422db2238d653c2d8f379c55e79b, which fixes a similar issue
with ceph-ansible.
(cherry picked from commit 5fc7707938d1c15506bfdbe02ae5b32ea885d0be)

This Victoria backport also includes
I4c65a428facdf6d4ce28d97a868589aeae4c856e, which drops lower-constraints
testing.  Per our PTG resolution [2] and general OpenStack resolution
[3], lower-constraints are not worth the extra work and confusion they
introduce.  This patch drops them along with all mentions.
(cherry picked from commit 604d85b6d2efc7d09ba8466d43c2d6591068d14e)

[1] https://github.com/pyca/cryptography/issues/5753
[2] http://lists.openstack.org/pipermail/openstack-discuss/2020-October/018445.html
[3] http://lists.openstack.org/pipermail/openstack-discuss/2020-December/019521.html

Change-Id: Ifaf1948ed5d42eebaa62d7bad375bbfc12b134d5
(cherry picked from commit 3dd6834a618d3ac83a6c0e301182f7b6a0897cf2)
Closes-Bug: #1915141