CI: fix kolla-ansible installation in stable/train
Installing kolla-ansible system-wide on CentOS 8 fails with:

    ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed
    project and thus we cannot accurately determine which files belong
    to it which would lead to only a partial uninstall.

This change switches to using pip --user when installing kolla-ansible,
as done in change Ifaf1948ed5d42eebaa62d7bad375bbfc12b134d5.

Change-Id: I4ac15e8ac4e2484e4aee0e942fabc2453a09d168