Fix installation errors with Python 2
Python 2 jobs recently started failing frequently with the following
error:

    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pbr>=2.0.0')

The root cause appears to be that indirect requirements are handled by
easy_install which doesn't like some index servers [1]. Try updating
setuptools first.

[1] https://github.com/googleapis/google-cloud-python/issues/3757#issuecomment-422384453

Change-Id: I95303e52f2b462ceda21abaa4097cc9291362d33