CI: Remove zun from project.yaml
It's been failing with:
ImportError: cannot import name 'transactional' from 'pyroute2.ipdb' (/var/lib/kolla/venv/lib/python3.12/site-packages/pyroute2/ipdb/__init__.py)

ipdb has been removed after long deprecation

Change-Id: I7db9a2274600d94894bc1da390e4f70132fe3965
Signed-off-by: Michal Nasiadka <mnasiadka@gmail.com>